baseURL = 'https://emre.xyz/'
languageCode = 'en-us'
title = 'emre.xyz | thought of delirehberi'
theme="archie"
copyright= "delirehberi"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true



disqusShortname = "delirehberi"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/delirehberi"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/delirehberi/"

[[params.social]]
name = "Bluesky"
icon = "at-sign"
url = "https://bsky.app/profile/emre.xyz"

[[params.social]]
name = "Youtube"
icon = "youtube"
url = "https://youtube.com/EmreYILMAZ"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/delirehberi"

[[params.social]]
name = "Nostr"
icon = "at-sign"
url = "https://satellite.earth/@delirehberi@emre.xyz"

[[params.social]]
name = "VCF"
icon = "phone"
url = "http://emre.xyz/me.vcf"

[[menu.main]]
name = "Articles"
url = "/"
weight = 1

[[menu.main]]
name = "Class"
url = "/class"
weight = 2

[[menu.main]]
name = "TIL"
url = "/til"
weight = 2 

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Subscribe"
url = "/subscribe"
weight = 4

enableEmoji = true
enableInlineShortcodes = true

[sitemap]
  changefreq = 'weekly'
  priority = 1.0

[markup.goldmark.renderer]
unsafe= true


[services]
  [services.googleAnalytics]
    ID = 'UA-61544632-1'

