baseURL = 'https://emre.xyz/'
languageCode = 'en-us'
title = 'emre.xyz | @delirehberi'

theme="archie"
copyright= "delirehberi"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

params.mode="toggle"

params.subtitle ="Hi, I’m Emre. I’m a developer, an art history student, a beginner DJ, an amateur poet, an improv theater enthusiast, and I live with seven cats. I love coding, dancing, learning languages, and trying new things. This blog is where I bring together all the scattered but passionate parts of my life. My contents are mostly in turkish, but I try to write some in english too. I hope you find something interesting here. Feel free to reach out if you want to chat or collaborate!"
 
[pagination]
pagerSize = 100

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/delirehberi"


[[params.social]]
name = "Youtube"
icon = "youtube"
url = "https://youtube.com/EmreYILMAZ"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/delirehberi"

[[params.social]]
name = "VCF"
icon = "phone"
url = "http://emre.xyz/me.vcf"

[[menu.main]]
name = "main"
url = "/"
weight = 1

[[menu.main]]
name = "cal"
url = "https://cal.emre.xyz"
weight = 2

[[menu.main]]
name = "nostr"
url = "https://nostr.emre.xyz"
weight = 3

[[menu.main]]
name = "til"
url = "/til"
weight = 3 

[[menu.main]]
name = "me"
url = "/about"
weight = 4

[[menu.main]]
name = "subscribe"
url = "/subscribe"
weight = 5

[[menu.main]]
name = "resume"
url = "/resume.pdf"
weight = 6

enableEmoji = true
enableInlineShortcodes = true

[sitemap]
  changefreq = 'weekly'
  priority = 1.0

[markup.goldmark.renderer]
unsafe= true



